-- CREAR BASE DE DATOS
CREATE USER hooka IDENTIFIED BY hooka DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO hooka;
ALTER USER hooka ACCOUNT UNLOCK;
-- CREACION DE TABLAS
CREATE TABLE empleados(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    APELLIDOS VARCHAR2(30),
    TELEFONO NUMBER(9) UNIQUE,
    DIRECCION VARCHAR2(30),
    PUESTO VARCHAR2(30) NOT NULL,
    CONSTRAINT CK_DNIEMP CHECK(REGEXP_LIKE(DNI,'[0-9]{8}[A-Z]{1}$')),
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DNI)
);
-- DNI LOS 8 PRIMEROS CARACTERES SON NUMEROS Y EL ULTIMO CARACTER UNA LETRA. 
-- TELEFONO DEBE SER TIPO UNICO, NO SE PUEDE REPETIR.
-- EL PUESTO NO DEBE SER VALOR NULO.

INSERT INTO empleados VALUES('00000001E','Ricardo','Milos','665544332','Calle Mirador,42','Vendedor');
INSERT INTO empleados VALUES('00000002F','Antonio','Recio','676655443','Calle Montepinar,12','Vendedor');

CREATE TABLE clientes(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    APELLIDOS VARCHAR2(30),
    TELEFONO NUMBER(9) UNIQUE,
    DIRECCION VARCHAR2(30),
    DNI_EMP VARCHAR2(9),
    CONSTRAINT CK_DNICLI CHECK(REGEXP_LIKE(DNI,'[0-9]{8}[A-Z]{1}$')),
    CONSTRAINT PK_CLIENTES PRIMARY KEY(DNI)
);
-- DNI LOS 8 PRIMEROS CARACTERES SON NUMEROS Y EL ULTIMO CARACTER UNA LETRA. 
-- TELEFONO DEBE SER TIPO UNICO, NO SE PUEDE REPETIR.

INSERT INTO clientes VALUES('11111111E','Berta','Escobar','668889765','Calle Ave,26','00000001E');
INSERT INTO clientes VALUES('11111112F','Fran','Pastor','679991876','Calle Paraiso,7','00000001E');

CREATE TABLE tienda(
    CODTIENDA VARCHAR2(5),
    DIRECCION VARCHAR2(30),
    LOCALIDAD VARCHAR2(30),
    PROVINCIA VARCHAR2(30) DEFAULT 'Sevilla',
    TELEFONO VARCHAR2(9) UNIQUE,
    CONSTRAINT CK_CODTIENDA1 CHECK(REGEXP_LIKE(CODTIENDA,'^[0]{4}')),
    CONSTRAINT PK_TIENDA PRIMARY KEY (CODTIENDA)
);

-- EL CODIGO TIENDA DEBEN SER 0 LOS CUATRO PRIMEROS CARACTERES
-- LA PROVINCIA POR DEFECTO ES SEVILLA.
-- TELEFONO DEBE SER TIPO UNICO, NO SE PUEDE REPETIR.

INSERT INTO tienda VALUES('0000A','Avenida España,2','Dos Hermanas','Sevilla','955552675');
INSERT INTO tienda VALUES('0000B','Avenida Reyes Catolicos,7','Dos Hermanas','Sevilla','955552678');

CREATE TABLE cachimbas(
    CODCACHIMBA VARCHAR2(5),
    MARCA VARCHAR2(30),
    MODELO VARCHAR2(30),
    PRECIO DECIMAL(10,2),
    FECHA_COMPRA DATE,
    DNI_CLIENTE VARCHAR2(9),
    CODTIENDA VARCHAR2(5),
    CONSTRAINT CK_CODCACHIMBA1 CHECK(REGEXP_LIKE(CODCACHIMBA,'^[1]{2}')),
    CONSTRAINT FECHA_COMPRA1 CHECK(TO_NUMBER(TO_CHAR(FECHA_COMPRA,'YYYY'))>=2022),
    CONSTRAINT PK_CACHIMBAS PRIMARY KEY (CODCACHIMBA),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES clientes(DNI),
    CONSTRAINT FK_TIENDA FOREIGN KEY (CODTIENDA) REFERENCES tienda(CODTIENDA)
);

INSERT INTO cachimbas VALUES('1111A','MR Shisha','Legend Mini 2.0','175,95','03/01/2022','11111111E','0000A');
INSERT INTO cachimbas VALUES('1112B','Steamulation','Megatron 2.0','239,95','03/01/2022','11111111E','0000A');

-- EL CODIGO CACHIMBA DEBEN SER 1 LOS DOS PRIMEROS CARACTERES
-- FECHA DE COMPRA DEBE SER SUPERIOR A 2022

CREATE TABLE accesorios(
    CODACCESORIO VARCHAR2(5),
    TIPO VARCHAR2(30),
    DESCRIPCION VARCHAR2(100),
    CODCACHIMBA VARCHAR(5),
    CONSTRAINT CK_CODACCESORIO1 CHECK(REGEXP_LIKE(CODACCESORIO,'^[2]{2}')),
    CONSTRAINT CK_TIPO1 CHECK(TIPO IN('Boquilla','Manguera','Tabaco','Plato','Provost','Punzon')),
    CONSTRAINT PK_ACCESORIOS PRIMARY KEY (CODACCESORIO),
    CONSTRAINT FK_CACHIMBA FOREIGN KEY (CODCACHIMBA) REFERENCES cachimbas(CODCACHIMBA)    
);

INSERT INTO accesorios VALUES('2222A','Boquilla','Su uso es para ponerlo encima de la manguera y no tener que usar todos la misma boquilla','1111A');
INSERT INTO accesorios VALUES('2222B','Boquilla','Su uso es para ponerlo encima de la manguera y no tener que usar todos la misma boquilla','1112B');

-- EL CODIGO ACCESORIOS DEBEN SER 2 LOS DOS PRIMEROS CARACTERES
-- TIPO DEBE SER BOQUILLA,MANGUERA,TABACO,PLATO,PROVOST O PUNZON.